### ISSUE TITLE
Only able to select NRO files in sdmc:/switch

### ISSUE THREAD

**Issue by AEAEAEAE4343** [TooTallNate/switch-nsp-forwarder#3]
Currently the tool only displays NRO files which are directly in the sdmc:/switch directory. But some NROs are stored elsewhere, like in subdirectories or in the case of HBL, on the SD card root.

I suggest implementing a file picker or maybe even just an advanced option to enter a full path to an NRO file manually.

**Comment by catfromplan9** [comment]
Since this has been resolved, can you please close the issue as solved? @TooTallNate

**Comment by AEAEAEAE4343** [comment]
The case of Homebrew Launcher has not been resolved. HBL is stored on SD root. My suggestion is making a config file where users can add extra search paths/direct paths to NROs.

**Comment by TooTallNate** [comment]
I'll be doing a new release very soon, which traverses subdirectories of the `switch` dir, includes the root level `hbmenu.nro` file and also allows for an explicit file picker. Stay tuned

**Comment by AEAEAEAE4343** [comment]
You’re a hero, I’m excited!

**Comment by TooTallNate** [comment]
v0.0.2 has been released
