### ISSUE TITLE
Create plaintext ncas in order to avoid needing keys

### ISSUE THREAD

**Issue by ITotalJustice** [TooTallNate/switch-nsp-forwarder#7]
Hi! Ncas have a few encryption methods, title key, standard crypto but they also can be plaintext.

Plaintext is exactly as the name suggests, they're not encrypted. In sphaira (my private-ish app) I generate plaintext ncas as to not require keys. Its minor thing as most users will have keys dumped, but having one less dependency is always nice :)

edit: here is a link, you set the encryption type in fs header https://switchbrew.org/wiki/NCA#FsHeader

you will still need to encrypt the nca header, but you can derive the nca header using spl

```c++
constexpr u8 HEADER_KEK_SRC[0x10] = {
    0x1F, 0x12, 0x91, 0x3A, 0x4A, 0xCB, 0xF0, 0x0D, 0x4C, 0xDE, 0x3A, 0xF6, 0xD5, 0x23, 0x88, 0x2A
};

constexpr u8 HEADER_KEY_SRC[0x20] = {
    0x5A, 0x3E, 0xD8, 0x4F, 0xDE, 0xC0, 0xD8, 0x26, 0x31, 0xF7, 0xE2, 0x5D, 0x19, 0x7B, 0xF5, 0xD0,
    0x1C, 0x9B, 0x7B, 0xFA, 0xF6, 0x28, 0x18, 0x3D, 0x71, 0xF6, 0x4D, 0x73, 0xF1, 0x50, 0xB9, 0xD2
};

// generate header kek
u8 header_kek[0x20];
R_TRY(splCryptoGenerateAesKek(HEADER_KEK_SRC, 0, 0, header_kek));
// gen header key 0
u8 key[0x20];
R_TRY(splCryptoGenerateAesKey(header_kek, HEADER_KEY_SRC, key));
// gen header key 1
R_TRY(splCryptoGenerateAesKey(header_kek, HEADER_KEY_SRC + 0x10, key + 0x10));
```

**Comment by TooTallNate** [comment]
That sounds great. Do you know if the underlying tool `hacbrewpack` supports generating in this mode?

**Comment by ITotalJustice** [comment]
Hmm, I'm not really familiar with hacbrewpack unfortunately. It shouldn't be too difficult to change it of it doesn't. Find the code that sets the encryption type in the fs header, change that to the value of none (that I linked in the wiki).

Then all the code that encrypts the fs header can be removed. Again, the nca header needs to be encrypted so keep that in.

Are you able to call libnx functions with your framework btw?

**Comment by TooTallNate** [comment]
> Are you able to call libnx functions with your framework btw?

Yes, see here: https://nxjs.n8.io/runtime/concepts/services

**Comment by TooTallNate** [comment]
Btw, maybe the `--plaintext` option is already doing what you're saying? https://github.com/TooTallNate/hacBrewPack/blob/master/main.c#L41

**Comment by ITotalJustice** [comment]
Yep that's it! You can actually keep the nca header encryption code the same, all that needs to change is how it gets the key. Instead of reading it from a file, generate it using my code that I posted in the first comment.
